# Site settings
title: "Allen Tools Resume Template"
description: "A resume template for allen.tools GitHub Pages."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Data Scientist and Engineer"
resume_title:                   "Professional Data/Computer Scientist and Engineer"
resume_contact_email:           "email@allen.tools"
resume_contact_telephone:       "1-(209)-677-7869"
resume_contact_address:         "Jacksonville, Florida"
resume_header_contact_info: "Jacksonville, Florida | 1-(209)-677-7869 | email@allen.tools"
resume_header_intro: "<p>I will never beat a computer at checkers, but build a tree for one to be a winner.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "no"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/kayfay/resume-template"
  resume_twitter_url:           "http://twitter.com/allen_tools"
  # resume_facebook_url:          "https://facebook.com/allentools"
  resume_linkedin_url:          "https://www.linkedin.com/in/allentools"
  resume_website_url:           "http://resume.allen.tools"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
